version: '3.8'

services:
  database:
    image: postgres:15
    container_name: conjur_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  conjur:
    image: cyberark/conjur
    container_name: conjur
    command: server
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY: "W0/nuw9tLUbCL3dOfh6JK3KzYRzUpNEKMQgZBxeGKkE="
      CONJUR_AUTHENTICATORS: authn
      CONJUR_TELEMETRY_ENABLED: 'false'
    depends_on:
      - database
    ports:
      - "3000:80"
    volumes:
      - conjur_data:/var/conjur/data

  client:
    image: cyberark/conjur-cli:8
    container_name: conjur_client
    depends_on:
      - conjur
    environment:
      CONJUR_APPLIANCE_URL: http://conjur:80
      CONJUR_ACCOUNT: demo
    command: sleep infinity
    volumes:
      - ./policies:/policies

volumes:
  postgres_data:
  conjur_data:
